#!/bin/bash
set -e

VERSION=${VERSION:-"latest"}

echo "Installing Paseo CLI (version: ${VERSION})..."

# Ensure npm is available
if ! command -v npm &> /dev/null; then
    echo "Error: npm is required. Please install Node.js first." >&2
    exit 1
fi

# Install Paseo CLI globally
if [[ "$VERSION" == "latest" ]]; then
    npm install -g --ignore-scripts @getpaseo/cli
else
    npm install -g --ignore-scripts @getpaseo/cli@"$VERSION"
fi
npm rebuild -g @getpaseo/cli 2>&1 || { echo "Error: paseo native binary setup failed" >&2; exit 1; }

# Verify installation
if command -v paseo &> /dev/null; then
    echo "Paseo CLI installed: $(paseo --version 2>&1 || echo 'version check skipped')"
else
    echo "Error: paseo not found on PATH after installation" >&2
    exit 1
fi

# Create .paseo directory in user home if it doesn't exist
REMOTE_USER="${_REMOTE_USER:-${_CONTAINER_USER:-root}}"
REMOTE_USER_HOME="${_REMOTE_USER_HOME:-$(getent passwd "$REMOTE_USER" 2>/dev/null | cut -d: -f6)}"
REMOTE_USER_HOME="${REMOTE_USER_HOME:-/home/vscode}"

# Create .paseo directory and set PASEO_HOME to the PVC-backed path
mkdir -p "${REMOTE_USER_HOME}/.paseo"

echo "export PASEO_HOME=${REMOTE_USER_HOME}/.paseo" > /etc/profile.d/paseo-home.sh
chmod 0644 /etc/profile.d/paseo-home.sh
if grep -q 'PASEO_HOME=' /etc/environment 2>/dev/null; then
    ESCAPED_HOME=$(printf '%s\n' "${REMOTE_USER_HOME}/.paseo" | sed 's/[&|]/\\&/g')
    sed -i "s|PASEO_HOME=.*|PASEO_HOME=${ESCAPED_HOME}|" /etc/environment
else
    echo "PASEO_HOME=${REMOTE_USER_HOME}/.paseo" >> /etc/environment
fi

echo "Paseo CLI installed successfully!"

# ---------------------------------------------------------------------------
# Plugins: generate a runtime sync script that installs declared plugins.
#
# `paseo plugin add`/`install` require a running daemon, so plugin install is a
# runtime step, not a build-time one. This feature writes
# /usr/local/bin/paseo-plugins-sync, which consumers call from postStartCommand
# (once per container start), NOT from a per-shell profile.d hook.
#
# Idempotency: re-adding an installed plugin re-clones the source before the
# daemon rejects it with "already configured" (~3-4s per plugin). The sync
# script keeps a marker file (spec -> plugin id) under PASEO_HOME and skips
# specs whose id is still present in `paseo plugin ls`, so subsequent starts
# do not re-clone.
#
# Data passing: option values are written to a separate env file
# (/usr/local/share/paseo-feature-plugins.env) and sourced by the sync script,
# NOT interpolated via sed. This avoids shell/sed injection when a plugin spec
# contains quotes, ampersands, backslashes, or sed metacharacters.
# ---------------------------------------------------------------------------
PLUGINS_RAW="${PLUGINS:-}"
ENABLE_PLUGINS="${ENABLEPLUGINS:-true}"

# Normalize the comma-separated list: trim each entry, drop empties.
NORMALIZED_PLUGINS=""
if [ -n "$PLUGINS_RAW" ]; then
    IFS=',' read -ra _PLUGINS <<< "$PLUGINS_RAW"
    for _p in "${_PLUGINS[@]}"; do
        _p="${_p#"${_p%%[![:space:]]*}"}"
        _p="${_p%"${_p##*[![:space:]]}"}"
        [ -n "$_p" ] || continue
        [ -n "$NORMALIZED_PLUGINS" ] && NORMALIZED_PLUGINS+=","
        NORMALIZED_PLUGINS+="$_p"
    done
fi

# Write option values to a separate env file (safe data passing — no sed/shell
# interpolation into the sync script). The sync script sources this file.
PLUGIN_ENV_FILE="/usr/local/share/paseo-feature-plugins.env"
rm -f "$PLUGIN_ENV_FILE"
cat > "$PLUGIN_ENV_FILE" <<PLUGIN_ENV_EOF
# Auto-generated by the paseo devcontainer feature. Sourced by paseo-plugins-sync.
PASEO_PLUGINS=\$(printf '%s' '$(printf '%s' "$NORMALIZED_PLUGINS" | sed "s/'/'\\\\''/g")')
PASEO_ENABLE_PLUGINS='$ENABLE_PLUGINS'
PASEO_HOME_FALLBACK='${REMOTE_USER_HOME}/.paseo'
PLUGIN_ENV_EOF
chmod 0644 "$PLUGIN_ENV_FILE"

# Remove any pre-existing file/symlink before writing the sync script (CWE-61:
# don't follow a pre-existing symlink and overwrite its target).
rm -f /usr/local/bin/paseo-plugins-sync
cat > /usr/local/bin/paseo-plugins-sync << 'PASEO_PLUGIN_SYNC_EOF'
#!/usr/bin/env bash
# Deliberately NOT `set -e`: this is a best-effort sync invoked from
# postStartCommand. It tolerates partial failures (daemon down, plugin
# already configured, network errors) and should not abort the container
# start. Each tolerated failure is guarded with `if`/`|| true`.
set -uo pipefail

# Auto-generated by the paseo devcontainer feature.
# Installs the plugins declared in the feature's "plugins" option idempotently.
# Requires a running Paseo daemon. Call from postStartCommand, not a per-shell hook.

# Load option values from the env file written at build time (safe data passing).
if [ -f /usr/local/share/paseo-feature-plugins.env ]; then
    # shellcheck disable=SC1091
    . /usr/local/share/paseo-feature-plugins.env
fi
PASEO_PLUGINS="${PASEO_PLUGINS:-}"
PASEO_ENABLE_PLUGINS="${PASEO_ENABLE_PLUGINS:-true}"
PASEO_HOME_FALLBACK="${PASEO_HOME_FALLBACK:-$HOME/.paseo}"

# Use the baked home fallback (resolved at build time) so OpenShift's HOME=/
# does not send markers and config lookups to /.paseo. PASEO_HOME from the
# environment (set by /etc/profile.d) still wins.
PASEO_HOME="${PASEO_HOME:-$PASEO_HOME_FALLBACK}"
CONFIG_JSON="$PASEO_HOME/config.json"
MARKER="$PASEO_HOME/.devcontainer-plugins-synced"
ADD_OUT="$(mktemp)"
trap 'rm -f "$ADD_OUT"' EXIT

log() { echo "paseo-plugins-sync: $*" >&2; }

# Node.js is required for JSON parsing and config editing. The paseo feature
# depends on node, but guard defensively in case the runtime PATH differs.
if ! command -v node >/dev/null 2>&1; then
    log "node not found on PATH; cannot sync plugins."
    exit 0
fi

# Wait briefly for the daemon to become reachable. A one-shot postStartCommand
# can race daemon startup; retrying avoids permanently skipping this start.
daemon_ready() {
    paseo plugin ls --json >/dev/null 2>&1
}
_attempts=0
_max_attempts=5
while [ "$_attempts" -lt "$_max_attempts" ]; do
    if daemon_ready; then break; fi
    _attempts=$((_attempts + 1))
    [ "$_attempts" -lt "$_max_attempts" ] || break
    log "daemon not reachable (attempt $_attempts/$_max_attempts); retrying in 2s..."
    sleep 2
done
if ! daemon_ready; then
    log "Paseo daemon not reachable after $_max_attempts attempts; skipping plugin sync (start it with 'paseo daemon start')."
    exit 0
fi

# Enable the daemon-wide plugin switch if requested. Setting the `plugins`
# feature option is explicit consent, so we do not prompt here. Only runs
# when plugins are actually declared — no point rewriting config.json when
# there is nothing to install.
enable_plugins_switch() {
    [ "$PASEO_ENABLE_PLUGINS" = "true" ] || return 0
    [ -f "$CONFIG_JSON" ] || { log "config.json not found at $CONFIG_JSON; cannot enable plugins."; return 0; }
    # Atomic write: write to a temp file then rename, so an interrupted write
    # or a concurrent daemon read does not corrupt config.json.
    if node -e '
        const fs = require("fs");
        const p = process.argv[1];
        const cfg = JSON.parse(fs.readFileSync(p, "utf8"));
        if (cfg.pluginsEnabled === true) process.exit(0);
        cfg.pluginsEnabled = true;
        const tmp = p + ".tmp." + process.pid;
        fs.writeFileSync(tmp, JSON.stringify(cfg, null, 2) + "\n");
        fs.renameSync(tmp, p);
    ' "$CONFIG_JSON" 2>/dev/null; then
        log "enabled global plugin switch"
    else
        log "could not enable plugin switch (config.json left unchanged)"
        return 0
    fi
    paseo reload --json >/dev/null 2>&1 || log "paseo reload failed (daemon may need a restart)"
}

# Print installed plugin ids, one per line.
installed_ids() {
    paseo plugin ls --json 2>/dev/null | node -e '
        let s = "";
        process.stdin.on("data", d => s += d);
        process.stdin.on("end", () => {
            try { console.log(JSON.parse(s).map(p => p.id).join("\n")); }
            catch { console.log(""); }
        });
    '
}

# Record spec -> id in the marker file (idempotent replacement of any old entry).
# Uses $(printf '\t') instead of a literal tab for portability.
record_marker() {
    local spec="$1" id="$2"
    mkdir -p "$PASEO_HOME" 2>/dev/null || true
    if [ -f "$MARKER" ]; then
        grep -v -F -- "$spec$(printf '\t')" "$MARKER" > "$MARKER.tmp" 2>/dev/null || true
        mv "$MARKER.tmp" "$MARKER" 2>/dev/null || true
    fi
    printf '%s\t%s\n' "$spec" "$id" >> "$MARKER" 2>/dev/null || true
}

# Look up the recorded id for a spec, if any.
marker_id_for() {
    [ -f "$MARKER" ] || return 0
    awk -F '\t' -v s="$1" '$1 == s { print $2; exit }' "$MARKER"
}

[ -n "$PASEO_PLUGINS" ] || { log "no plugins configured"; exit 0; }

enable_plugins_switch

# Split on commas. Each spec may contain spaces (e.g. "owner/repo --ref main").
IFS=',' read -ra SPECS <<< "$PASEO_PLUGINS"

for spec in "${SPECS[@]}"; do
    [ -n "$spec" ] || continue

    # Skip if the marker has this spec and its id is still installed.
    marker_id="$(marker_id_for "$spec")"
    if [ -n "$marker_id" ] && printf '%s\n' "$(installed_ids)" | grep -Fxq "$marker_id"; then
        log "already installed: $spec ($marker_id)"
        continue
    fi

    # Split the spec into words so flags (e.g. "--ref main") become separate
    # argv elements. Local paths (absolute or dot-prefixed relative, including
    # "../") use `install`; everything else is a Git source for `add`.
    read -ra SPEC_ARGS <<< "$spec"
    case "${SPEC_ARGS[0]}" in
        /*|./*|../*) cmd=(paseo plugin install "${SPEC_ARGS[@]}") ;;
        *)           cmd=(paseo plugin add "${SPEC_ARGS[@]}") ;;
    esac

    log "installing: $spec"
    before="$(installed_ids)"
    if "${cmd[@]}" >"$ADD_OUT" 2>&1; then
        after="$(installed_ids)"
        new_id=""
        while IFS= read -r id; do
            [ -n "$id" ] || continue
            if ! printf '%s\n' "$before" | grep -Fxq "$id"; then
                new_id="$id"
                break
            fi
        done <<< "$after"
        if [ -n "$new_id" ]; then
            record_marker "$spec" "$new_id"
            log "installed: $spec ($new_id)"
        else
            log "installed: $spec (id could not be determined)"
        fi
    else
        # Tolerate "already configured" (e.g. marker missing but plugin present).
        if grep -q "already configured" "$ADD_OUT" 2>/dev/null; then
            log "already configured: $spec (skipped)"
        else
            log "failed: $spec"
            sed 's/^/  /' "$ADD_OUT" >&2 2>/dev/null || true
        fi
    fi
done

log "done"
PASEO_PLUGIN_SYNC_EOF

chmod 0755 /usr/local/bin/paseo-plugins-sync
echo "paseo: runtime plugin sync script at /usr/local/bin/paseo-plugins-sync"


# Permission fix: only fix permissions on paseo-specific dirs, not all of /home/vscode
echo "Paseo: fixing permissions for OpenShift compatibility"
for dir in "${REMOTE_USER_HOME}/.paseo" "${REMOTE_USER_HOME}/.config/environment.d" "${REMOTE_USER_HOME}/.agents"; do
  if [[ -d "$dir" ]]; then
    chgrp -R 0 "$dir" 2>/dev/null || true
    chmod -R g+rwX "$dir" 2>/dev/null || true
  fi
done
# Make home dir group-writable for OpenShift random UID compat (group 0 can create dirs)
# but don't recursively chmod (only the dir itself, not all contents)
chgrp 0 "${REMOTE_USER_HOME}" 2>/dev/null || true
chmod 2775 "${REMOTE_USER_HOME}" 2>/dev/null || true

# Create a runtime-writable bin dir instead of making /usr/local/bin group-writable
RUNTIME_BIN="/usr/local/share/runtime-bin"
mkdir -p "$RUNTIME_BIN"
chgrp 0 "$RUNTIME_BIN" 2>/dev/null || true
chmod g+w "$RUNTIME_BIN" 2>/dev/null || true
# Add to PATH via profile.d
echo "export PATH=\"\$PATH:/usr/local/share/runtime-bin\"" > /etc/profile.d/runtime-bin.sh
chmod 0644 /etc/profile.d/runtime-bin.sh

# Fix /usr/local/share/agent-config so runtime UID can write to config dirs
# (devin, claude, codex, opencode, kilo, gascity, herdr symlinks point here)
chgrp -R 0 /usr/local/share/agent-config 2>/dev/null || true
chmod -R g+rwX /usr/local/share/agent-config 2>/dev/null || true

# Defer permission fix to runtime via profile.d, so it catches dirs created by later features
# Non-recursive: only fix the dir itself (setgid bit on home ensures children inherit group 0)
cat > /etc/profile.d/paseo-perms.sh << 'PERMEOF'
# Fix permissions on agent dirs at shell startup (catches dirs created after paseo install)
for dir in "$HOME/.paseo" "$HOME/.agents" "$HOME/.config/environment.d"; do
  if [ -d "$dir" ]; then
    chgrp 0 "$dir" 2>/dev/null || true
    chmod g+rwX "$dir" 2>/dev/null || true
  fi
done
PERMEOF
chmod 0644 /etc/profile.d/paseo-perms.sh
